model_list:
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: vertex_ai/claude-3-5-sonnet@20240620
      vertex_ai_project: "os.environ/ANTHROPIC_VERTEX_PROJECT_ID"
      vertex_ai_location: "os.environ/CLOUD_ML_REGION"
  - model_name: claude-3-5-haiku
    litellm_params:
      model: vertex_ai/claude-3-5-haiku@20241022
      vertex_ai_project: "os.environ/ANTHROPIC_VERTEX_PROJECT_ID"
      vertex_ai_location: "os.environ/CLOUD_ML_REGION"
  - model_name: claude-3-opus
    litellm_params:
      model: vertex_ai/claude-3-opus@20240229
      vertex_ai_project: "os.environ/ANTHROPIC_VERTEX_PROJECT_ID"
      vertex_ai_location: "os.environ/CLOUD_ML_REGION"
  - model_name: gemini-1.5-pro
    litellm_params:
      model: vertex_ai/gemini-1.5-pro
      vertex_ai_project: "os.environ/ANTHROPIC_VERTEX_PROJECT_ID"
      vertex_ai_location: "os.environ/CLOUD_ML_REGION"
  - model_name: gemini-1.5-flash
    litellm_params:
      model: vertex_ai/gemini-1.5-flash
      vertex_ai_project: "os.environ/ANTHROPIC_VERTEX_PROJECT_ID"
      vertex_ai_location: "os.environ/CLOUD_ML_REGION"

general_settings:
  disable_master_key: true # Disable API key requirements for local development within the workstation
